# See https://cloud.google.com/appengine/docs/flexible/nodejs/reference/app-yaml

runtime: nodejs
env: flex

handlers:
  - url: /.*
    script: app.js
    secure: always

resources:
  cpu: 1
  memory_gb: 1

liveness_check:
  path: "/health"

readiness_check:
  path: "/health"

env_variables:
  NODE_ENV: "production"
